# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:24:51+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class ApplyParametersRequest(BaseModel):
    applyAll: Optional[bool] = Field(
        None,
        description='Whether to apply instance-level parameter group to all nodes. If set to true, users are restricted from specifying individual nodes, and `ApplyParameters` updates all nodes within the instance.',
    )
    nodeIds: Optional[List[str]] = Field(
        None,
        description='Nodes to which the instance-level parameter group is applied.',
    )


class ApplySoftwareUpdateRequest(BaseModel):
    applyAll: Optional[bool] = Field(
        None,
        description='Whether to apply the update to all nodes. If set to true, will explicitly restrict users from specifying any nodes, and apply software update to all nodes (where applicable) within the instance.',
    )
    nodeIds: Optional[List[str]] = Field(
        None,
        description='Nodes to which we should apply the update to. Note all the selected nodes are updated in parallel.',
    )


class CancelOperationRequest(BaseModel):
    pass


class Date(BaseModel):
    day: Optional[int] = Field(
        None,
        description="Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
    )
    month: Optional[int] = Field(
        None,
        description='Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.',
    )
    year: Optional[int] = Field(
        None,
        description='Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.',
    )


class Empty(BaseModel):
    pass


class GoogleCloudMemcacheV1beta2OperationMetadata(BaseModel):
    apiVersion: Optional[str] = Field(
        None, description='Output only. API version used to start the operation.'
    )
    cancelRequested: Optional[bool] = Field(
        None,
        description='Output only. Identifies whether the user has requested cancellation of the operation. Operations that have successfully been cancelled have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`.',
    )
    createTime: Optional[str] = Field(
        None, description='Output only. Time when the operation was created.'
    )
    endTime: Optional[str] = Field(
        None, description='Output only. Time when the operation finished running.'
    )
    statusDetail: Optional[str] = Field(
        None, description='Output only. Human-readable status of the operation, if any.'
    )
    target: Optional[str] = Field(
        None,
        description='Output only. Server-defined resource path for the target of the operation.',
    )
    verb: Optional[str] = Field(
        None, description='Output only. Name of the verb executed by the operation.'
    )


class GoogleCloudMemcacheV1beta2ZoneMetadata(BaseModel):
    pass


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    CREATING = 'CREATING'
    READY = 'READY'
    UPDATING = 'UPDATING'
    REPAIRING = 'REPAIRING'
    DELETING = 'DELETING'
    ERROR = 'ERROR'


class GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSchedule(BaseModel):
    canReschedule: Optional[bool] = Field(
        None,
        description='This field is deprecated, and will be always set to true since reschedule can happen multiple times now. This field should not be removed until all service producers remove this for their customers.',
    )
    endTime: Optional[str] = Field(
        None, description='The scheduled end time for the maintenance.'
    )
    rolloutManagementPolicy: Optional[str] = Field(
        None,
        description='The rollout management policy this maintenance schedule is associated with. When doing reschedule update request, the reschedule should be against this given policy.',
    )
    scheduleDeadlineTime: Optional[str] = Field(
        None,
        description="schedule_deadline_time is the time deadline any schedule start time cannot go beyond, including reschedule. It's normally the initial schedule start time plus maintenance window length (1 day or 1 week). Maintenance cannot be scheduled to start beyond this deadline.",
    )
    startTime: Optional[str] = Field(
        None, description='The scheduled start time for the maintenance.'
    )


class GoogleCloudSaasacceleratorManagementProvidersV1NotificationParameter(BaseModel):
    values: Optional[List[str]] = Field(
        None,
        description="Optional. Array of string values. e.g. instance's replica information.",
    )


class GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource(BaseModel):
    resourceType: Optional[str] = Field(
        None,
        description="Type of the resource. This can be either a GCP resource or a custom one (e.g. another cloud provider's VM). For GCP compute resources use singular form of the names listed in GCP compute API documentation (https://cloud.google.com/compute/docs/reference/rest/v1/), prefixed with 'compute-', for example: 'compute-instance', 'compute-disk', 'compute-autoscaler'.",
    )
    resourceUrl: Optional[str] = Field(
        None,
        description='URL identifying the resource, e.g. "https://www.googleapis.com/compute/v1/projects/...)".',
    )


class GoogleCloudSaasacceleratorManagementProvidersV1SloEligibility(BaseModel):
    eligible: Optional[bool] = Field(
        None, description='Whether an instance is eligible or ineligible.'
    )
    reason: Optional[str] = Field(
        None,
        description='User-defined reason for the current value of instance eligibility. Usually, this can be directly mapped to the internal state. An empty reason is allowed.',
    )


class MemcacheVersion(Enum):
    MEMCACHE_VERSION_UNSPECIFIED = 'MEMCACHE_VERSION_UNSPECIFIED'
    MEMCACHE_1_5 = 'MEMCACHE_1_5'


class State1(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    CREATING = 'CREATING'
    READY = 'READY'
    UPDATING = 'UPDATING'
    DELETING = 'DELETING'
    PERFORMING_MAINTENANCE = 'PERFORMING_MAINTENANCE'


class Code(Enum):
    CODE_UNSPECIFIED = 'CODE_UNSPECIFIED'
    ZONE_DISTRIBUTION_UNBALANCED = 'ZONE_DISTRIBUTION_UNBALANCED'


class InstanceMessage(BaseModel):
    code: Optional[Code] = Field(
        None, description='A code that correspond to one type of user-facing message.'
    )
    message: Optional[str] = Field(
        None,
        description='Message on memcached instance which will be exposed to users.',
    )


class Location(BaseModel):
    displayName: Optional[str] = Field(
        None,
        description='The friendly name for this location, typically a nearby city name. For example, "Tokyo".',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Cross-service attributes for the location. For example {"cloud.googleapis.com/region": "us-east1"}',
    )
    locationId: Optional[str] = Field(
        None,
        description='The canonical id for this location. For example: `"us-east1"`.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Service-specific metadata. For example the available capacity at the given location.',
    )
    name: Optional[str] = Field(
        None,
        description='Resource name for the location, which may vary between implementations. For example: `"projects/example-project/locations/us-east1"`',
    )


class State2(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    READY = 'READY'
    DELETING = 'DELETING'


class MaintenanceSchedule(BaseModel):
    endTime: Optional[str] = Field(
        None,
        description='Output only. The end time of any upcoming scheduled maintenance for this instance.',
    )
    scheduleDeadlineTime: Optional[str] = Field(
        None,
        description='Output only. The deadline that the maintenance schedule start time can not go beyond, including reschedule.',
    )
    startTime: Optional[str] = Field(
        None,
        description='Output only. The start time of any upcoming scheduled maintenance for this instance.',
    )


class MemcacheParameters(BaseModel):
    id: Optional[str] = Field(
        None,
        description='Output only. The unique ID associated with this set of parameters. Users can use this id to determine if the parameters associated with the instance differ from the parameters associated with the nodes. A discrepancy between parameter ids can inform users that they may need to take action to apply parameters on nodes.',
    )
    params: Optional[Dict[str, str]] = Field(
        None,
        description='User defined set of parameters to use in the memcached process.',
    )


class State3(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    CREATING = 'CREATING'
    READY = 'READY'
    DELETING = 'DELETING'
    UPDATING = 'UPDATING'


class Node(BaseModel):
    host: Optional[str] = Field(
        None,
        description='Output only. Hostname or IP address of the Memcached node used by the clients to connect to the Memcached server on this node.',
    )
    nodeId: Optional[str] = Field(
        None,
        description='Output only. Identifier of the Memcached node. The node id does not include project or location like the Memcached instance name.',
    )
    parameters: Optional[MemcacheParameters] = Field(
        None, description='User defined parameters currently applied to the node.'
    )
    port: Optional[int] = Field(
        None,
        description='Output only. The port number of the Memcached server on this node.',
    )
    state: Optional[State3] = Field(
        None, description='Output only. Current state of the Memcached node.'
    )
    updateAvailable: Optional[bool] = Field(
        None,
        description='Output only. Returns true if there is an update waiting to be applied',
    )
    zone: Optional[str] = Field(
        None, description='Output only. Location (GCP Zone) for the Memcached node.'
    )


class NodeConfig(BaseModel):
    cpuCount: Optional[int] = Field(
        None, description='Required. Number of cpus per Memcached node.'
    )
    memorySizeMb: Optional[int] = Field(
        None, description='Required. Memory size in MiB for each Memcached node.'
    )


class OperationMetadata(BaseModel):
    apiVersion: Optional[str] = Field(
        None, description='Output only. API version used to start the operation.'
    )
    cancelRequested: Optional[bool] = Field(
        None,
        description='Output only. Identifies whether the user has requested cancellation of the operation. Operations that have successfully been cancelled have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`.',
    )
    createTime: Optional[str] = Field(
        None, description='Output only. Time when the operation was created.'
    )
    endTime: Optional[str] = Field(
        None, description='Output only. Time when the operation finished running.'
    )
    statusDetail: Optional[str] = Field(
        None, description='Output only. Human-readable status of the operation, if any.'
    )
    target: Optional[str] = Field(
        None,
        description='Output only. Server-defined resource path for the target of the operation.',
    )
    verb: Optional[str] = Field(
        None, description='Output only. Name of the verb executed by the operation.'
    )


class RescheduleType(Enum):
    RESCHEDULE_TYPE_UNSPECIFIED = 'RESCHEDULE_TYPE_UNSPECIFIED'
    IMMEDIATE = 'IMMEDIATE'
    NEXT_AVAILABLE_WINDOW = 'NEXT_AVAILABLE_WINDOW'
    SPECIFIC_TIME = 'SPECIFIC_TIME'


class RescheduleMaintenanceRequest(BaseModel):
    rescheduleType: Optional[RescheduleType] = Field(
        None,
        description='Required. If reschedule type is SPECIFIC_TIME, must set up schedule_time as well.',
    )
    scheduleTime: Optional[str] = Field(
        None,
        description='Timestamp when the maintenance shall be rescheduled to if reschedule_type=SPECIFIC_TIME, in RFC 3339 format, for example `2012-11-15T16:19:00.094Z`.',
    )


class Day(Enum):
    DAY_OF_WEEK_UNSPECIFIED = 'DAY_OF_WEEK_UNSPECIFIED'
    MONDAY = 'MONDAY'
    TUESDAY = 'TUESDAY'
    WEDNESDAY = 'WEDNESDAY'
    THURSDAY = 'THURSDAY'
    FRIDAY = 'FRIDAY'
    SATURDAY = 'SATURDAY'
    SUNDAY = 'SUNDAY'


class Status(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class TimeOfDay(BaseModel):
    hours: Optional[int] = Field(
        None,
        description='Hours of day in 24 hour format. Should be from 0 to 23. An API may choose to allow the value "24:00:00" for scenarios like business closing time.',
    )
    minutes: Optional[int] = Field(
        None, description='Minutes of hour of day. Must be from 0 to 59.'
    )
    nanos: Optional[int] = Field(
        None,
        description='Fractions of seconds in nanoseconds. Must be from 0 to 999,999,999.',
    )
    seconds: Optional[int] = Field(
        None,
        description='Seconds of minutes of the time. Must normally be from 0 to 59. An API may allow the value 60 if it allows leap-seconds.',
    )


class UpdateParametersRequest(BaseModel):
    parameters: Optional[MemcacheParameters] = Field(
        None, description='The parameters to apply to the instance.'
    )
    updateMask: Optional[str] = Field(
        None, description='Required. Mask of fields to update.'
    )


class Channel(Enum):
    UPDATE_CHANNEL_UNSPECIFIED = 'UPDATE_CHANNEL_UNSPECIFIED'
    EARLIER = 'EARLIER'
    LATER = 'LATER'
    WEEK1 = 'WEEK1'
    WEEK2 = 'WEEK2'
    WEEK5 = 'WEEK5'


class WeeklyMaintenanceWindow(BaseModel):
    day: Optional[Day] = Field(
        None,
        description='Required. Allows to define schedule that runs specified day of the week.',
    )
    duration: Optional[str] = Field(
        None, description='Required. Duration of the time window.'
    )
    startTime: Optional[TimeOfDay] = Field(
        None, description='Required. Start time of the window in UTC.'
    )


class ZoneMetadata(BaseModel):
    pass


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class DailyCycle(BaseModel):
    duration: Optional[str] = Field(
        None,
        description='Output only. Duration of the time window, set by service producer.',
    )
    startTime: Optional[TimeOfDay] = Field(
        None, description='Time within the day to start the operations.'
    )


class DenyMaintenancePeriod(BaseModel):
    endDate: Optional[Date] = Field(
        None,
        description='Deny period end date. This can be: * A full date, with non-zero year, month and day values. * A month and day value, with a zero year. Allows recurring deny periods each year. Date matching this period will have to be before the end.',
    )
    startDate: Optional[Date] = Field(
        None,
        description='Deny period start date. This can be: * A full date, with non-zero year, month and day values. * A month and day value, with a zero year. Allows recurring deny periods each year. Date matching this period will have to be the same or after the start.',
    )
    time: Optional[TimeOfDay] = Field(
        None,
        description='Time in UTC when the Blackout period starts on start_date and ends on end_date. This can be: * Full time. * All zeros for 00:00:00 UTC',
    )


class GoogleCloudMemcacheV1beta2LocationMetadata(BaseModel):
    availableZones: Optional[Dict[str, GoogleCloudMemcacheV1beta2ZoneMetadata]] = Field(
        None,
        description='Output only. The set of available zones in the location. The map is keyed by the lowercase ID of each zone, as defined by GCE. These keys can be specified in the `zones` field when creating a Memcached instance.',
    )


class GoogleCloudMemcacheV1beta2MaintenancePolicy(BaseModel):
    createTime: Optional[str] = Field(
        None, description='Output only. The time when the policy was created.'
    )
    description: Optional[str] = Field(
        None,
        description='Description of what this policy is for. Create/Update methods return INVALID_ARGUMENT if the length is greater than 512.',
    )
    updateTime: Optional[str] = Field(
        None, description='Output only. The time when the policy was updated.'
    )
    weeklyMaintenanceWindow: Optional[List[WeeklyMaintenanceWindow]] = Field(
        None,
        description='Required. Maintenance window that is applied to resources covered by this policy. Minimum 1. For the current version, the maximum number of weekly_maintenance_windows is expected to be one.',
    )


class GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility(BaseModel):
    eligibilities: Optional[
        Dict[str, GoogleCloudSaasacceleratorManagementProvidersV1SloEligibility]
    ] = Field(
        None,
        description='An entry in the eligibilities map specifies an eligibility for a particular SLI for the given instance. The SLI key in the name must be a valid SLI name specified in the Eligibility Exporter binary flags otherwise an error will be emitted by Eligibility Exporter and the oncaller will be alerted. If an SLI has been defined in the binary flags but the eligibilities map does not contain it, the corresponding SLI time series will not be emitted by the Eligibility Exporter. This ensures a smooth rollout and compatibility between the data produced by different versions of the Eligibility Exporters. If eligibilities map contains a key for an SLI which has not been declared in the binary flags, there will be an error message emitted in the Eligibility Exporter log and the metric for the SLI in question will not be emitted.',
    )


class Instance(BaseModel):
    authorizedNetwork: Optional[str] = Field(
        None,
        description='The full name of the Google Compute Engine [network](https://cloud.google.com/vpc/docs/vpc) to which the instance is connected. If left unspecified, the `default` network will be used.',
    )
    createTime: Optional[str] = Field(
        None, description='Output only. The time the instance was created.'
    )
    discoveryEndpoint: Optional[str] = Field(
        None, description='Output only. Endpoint for the Discovery API.'
    )
    displayName: Optional[str] = Field(
        None,
        description='User provided name for the instance, which is only used for display purposes. Cannot be more than 80 characters.',
    )
    instanceMessages: Optional[List[InstanceMessage]] = Field(
        None,
        description='List of messages that describe the current state of the Memcached instance.',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Resource labels to represent user-provided metadata. Refer to cloud documentation on labels for more details. https://cloud.google.com/compute/docs/labeling-resources',
    )
    maintenancePolicy: Optional[GoogleCloudMemcacheV1beta2MaintenancePolicy] = Field(
        None,
        description='The maintenance policy for the instance. If not provided, the maintenance event will be performed based on Memorystore internal rollout schedule.',
    )
    maintenanceSchedule: Optional[MaintenanceSchedule] = Field(
        None, description='Output only. Published maintenance schedule.'
    )
    memcacheFullVersion: Optional[str] = Field(
        None,
        description='Output only. The full version of memcached server running on this instance. System automatically determines the full memcached version for an instance based on the input MemcacheVersion. The full version format will be "memcached-1.5.16".',
    )
    memcacheNodes: Optional[List[Node]] = Field(
        None,
        description='Output only. List of Memcached nodes. Refer to Node message for more details.',
    )
    memcacheVersion: Optional[MemcacheVersion] = Field(
        None,
        description='The major version of Memcached software. If not provided, latest supported version will be used. Currently the latest supported major version is `MEMCACHE_1_5`. The minor version will be automatically determined by our system based on the latest supported minor version.',
    )
    name: Optional[str] = Field(
        None,
        description='Required. Unique name of the resource in this scope including project and location using the form: `projects/{project_id}/locations/{location_id}/instances/{instance_id}` Note: Memcached instances are managed and addressed at the regional level so `location_id` here refers to a Google Cloud region; however, users may choose which zones Memcached nodes should be provisioned in within an instance. Refer to zones field for more details.',
    )
    nodeConfig: Optional[NodeConfig] = Field(
        None, description='Required. Configuration for Memcached nodes.'
    )
    nodeCount: Optional[int] = Field(
        None, description='Required. Number of nodes in the Memcached instance.'
    )
    parameters: Optional[MemcacheParameters] = Field(
        None,
        description='User defined parameters to apply to the memcached process on each node.',
    )
    state: Optional[State1] = Field(
        None, description='Output only. The state of this Memcached instance.'
    )
    updateAvailable: Optional[bool] = Field(
        None,
        description='Output only. Returns true if there is an update waiting to be applied',
    )
    updateTime: Optional[str] = Field(
        None, description='Output only. The time the instance was updated.'
    )
    zones: Optional[List[str]] = Field(
        None,
        description='Zones in which Memcached nodes should be provisioned. Memcached nodes will be equally distributed across these zones. If not provided, the service will by default create nodes in all zones in the region for the instance.',
    )


class ListInstancesResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='Token to retrieve the next page of results, or empty if there are no more results in the list.',
    )
    resources: Optional[List[Instance]] = Field(
        None,
        description='A list of Memcached instances in the project in the specified location, or across all locations. If the `location_id` in the parent field of the request is "-", all regions available to the project are queried, and the results aggregated.',
    )
    unreachable: Optional[List[str]] = Field(
        None, description='Locations that could not be reached.'
    )


class ListLocationsResponse(BaseModel):
    locations: Optional[List[Location]] = Field(
        None,
        description='A list of locations that matches the specified filter in the request.',
    )
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )


class LocationMetadata(BaseModel):
    availableZones: Optional[Dict[str, ZoneMetadata]] = Field(
        None,
        description='Output only. The set of available zones in the location. The map is keyed by the lowercase ID of each zone, as defined by GCE. These keys can be specified in the `zones` field when creating a Memcached instance.',
    )


class Operation(BaseModel):
    done: Optional[bool] = Field(
        None,
        description='If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available.',
    )
    error: Optional[Status] = Field(
        None,
        description='The error result of the operation in case of failure or cancellation.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.',
    )
    name: Optional[str] = Field(
        None,
        description='The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`.',
    )
    response: Optional[Dict[str, Any]] = Field(
        None,
        description='The normal response of the operation in case of success. If the original method returns no data on success, such as `Delete`, the response is `google.protobuf.Empty`. If the original method is standard `Get`/`Create`/`Update`, the response should be the resource. For other methods, the response should have the type `XxxResponse`, where `Xxx` is the original method name. For example, if the original method name is `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.',
    )


class Schedule(BaseModel):
    day: Optional[Day] = Field(
        None,
        description='Allows to define schedule that runs specified day of the week.',
    )
    duration: Optional[str] = Field(
        None,
        description='Output only. Duration of the time window, set by service producer.',
    )
    startTime: Optional[TimeOfDay] = Field(
        None, description='Time within the window to start the operations.'
    )


class WeeklyCycle(BaseModel):
    schedule: Optional[List[Schedule]] = Field(
        None,
        description='User can specify multiple windows in a week. Minimum of 1 window.',
    )


class GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata(BaseModel):
    location: Optional[str] = Field(
        None,
        description='The location of the node, if different from instance location.',
    )
    nodeId: Optional[str] = Field(
        None,
        description='The id of the node. This should be equal to SaasInstanceNode.node_id.',
    )
    perSliEligibility: Optional[
        GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility
    ] = Field(
        None,
        description='If present, this will override eligibility for the node coming from instance or exclusions for specified SLIs.',
    )


class GoogleCloudSaasacceleratorManagementProvidersV1SloMetadata(BaseModel):
    nodes: Optional[
        List[GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata]
    ] = Field(
        None,
        description='Optional. List of nodes. Some producers need to use per-node metadata to calculate SLO. This field allows such producers to publish per-node SLO meta data, which will be consumed by SSA Eligibility Exporter and published in the form of per node metric to Monarch.',
    )
    perSliEligibility: Optional[
        GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility
    ] = Field(
        None,
        description='Optional. Multiple per-instance SLI eligibilities which apply for individual SLIs.',
    )
    tier: Optional[str] = Field(
        None,
        description='Name of the SLO tier the Instance belongs to. This name will be expected to match the tiers specified in the service SLO configuration. Field is mandatory and must not be empty.',
    )


class ListOperationsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )
    operations: Optional[List[Operation]] = Field(
        None,
        description='A list of operations that matches the specified filter in the request.',
    )


class MaintenanceWindow(BaseModel):
    dailyCycle: Optional[DailyCycle] = Field(None, description='Daily cycle.')
    weeklyCycle: Optional[WeeklyCycle] = Field(None, description='Weekly cycle.')


class UpdatePolicy(BaseModel):
    channel: Optional[Channel] = Field(
        None, description='Optional. Relative scheduling channel applied to resource.'
    )
    denyMaintenancePeriods: Optional[List[DenyMaintenancePeriod]] = Field(
        None,
        description='Deny Maintenance Period that is applied to resource to indicate when maintenance is forbidden. User can specify zero or more non-overlapping deny periods. Maximum number of deny_maintenance_periods expected is one.',
    )
    window: Optional[MaintenanceWindow] = Field(
        None,
        description='Optional. Maintenance window that is applied to resources covered by this policy.',
    )


class MaintenancePolicy(BaseModel):
    createTime: Optional[str] = Field(
        None, description='Output only. The time when the resource was created.'
    )
    description: Optional[str] = Field(
        None,
        description='Optional. Description of what this policy is for. Create/Update methods return INVALID_ARGUMENT if the length is greater than 512.',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Optional. Resource labels to represent user provided metadata. Each label is a key-value pair, where both the key and the value are arbitrary strings provided by the user.',
    )
    name: Optional[str] = Field(
        None,
        description='Required. MaintenancePolicy name using the form: `projects/{project_id}/locations/{location_id}/maintenancePolicies/{maintenance_policy_id}` where {project_id} refers to a GCP consumer project ID, {location_id} refers to a GCP region/zone, {maintenance_policy_id} must be 1-63 characters long and match the regular expression `[a-z0-9]([-a-z0-9]*[a-z0-9])?`.',
    )
    state: Optional[State2] = Field(
        None, description='Optional. The state of the policy.'
    )
    updatePolicy: Optional[UpdatePolicy] = Field(
        None, description='Maintenance policy applicable to instance update.'
    )
    updateTime: Optional[str] = Field(
        None, description='Output only. The time when the resource was updated.'
    )


class GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings(BaseModel):
    exclude: Optional[bool] = Field(
        None,
        description='Optional. Exclude instance from maintenance. When true, rollout service will not attempt maintenance on the instance. Rollout service will include the instance in reported rollout progress as not attempted.',
    )
    isRollback: Optional[bool] = Field(
        None,
        description='Optional. If the update call is triggered from rollback, set the value as true.',
    )
    maintenancePolicies: Optional[Dict[str, MaintenancePolicy]] = Field(
        None,
        description='Optional. The MaintenancePolicies that have been attached to the instance. The key must be of the type name of the oneof policy name defined in MaintenancePolicy, and the embedded policy must define the same policy type. For details, please refer to go/cloud-saas-mw-ug. Should not be set if maintenance_policy_names is set. If only the name is needed, then only populate MaintenancePolicy.name.',
    )


class GoogleCloudSaasacceleratorManagementProvidersV1Instance(BaseModel):
    consumerDefinedName: Optional[str] = Field(
        None,
        description='consumer_defined_name is the name of the instance set by the service consumers. Generally this is different from the `name` field which reperesents the system-assigned id of the instance which the service consumers do not recognize. This is a required field for tenants onboarding to Maintenance Window notifications (go/slm-rollout-maintenance-policies#prerequisites).',
    )
    createTime: Optional[str] = Field(
        None, description='Output only. Timestamp when the resource was created.'
    )
    instanceType: Optional[str] = Field(
        None,
        description="Optional. The instance_type of this instance of format: projects/{project_number}/locations/{location_id}/instanceTypes/{instance_type_id}. Instance Type represents a high-level tier or SKU of the service that this instance belong to. When enabled(eg: Maintenance Rollout), Rollout uses 'instance_type' along with 'software_versions' to determine whether instance needs an update or not.",
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Optional. Resource labels to represent user provided metadata. Each label is a key-value pair, where both the key and the value are arbitrary strings provided by the user.',
    )
    maintenancePolicyNames: Optional[Dict[str, str]] = Field(
        None,
        description='Optional. The MaintenancePolicies that have been attached to the instance. The key must be of the type name of the oneof policy name defined in MaintenancePolicy, and the referenced policy must define the same policy type. For details, please refer to go/cloud-saas-mw-ug. Should not be set if maintenance_settings.maintenance_policies is set.',
    )
    maintenanceSchedules: Optional[
        Dict[str, GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSchedule]
    ] = Field(
        None,
        description='The MaintenanceSchedule contains the scheduling information of published maintenance schedule with same key as software_versions.',
    )
    maintenanceSettings: Optional[
        GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings
    ] = Field(
        None, description='Optional. The MaintenanceSettings associated with instance.'
    )
    name: Optional[str] = Field(
        None,
        description='Unique name of the resource. It uses the form: `projects/{project_number}/locations/{location_id}/instances/{instance_id}` Note: This name is passed, stored and logged across the rollout system. So use of consumer project_id or any other consumer PII in the name is strongly discouraged for wipeout (go/wipeout) compliance. See go/elysium/project_ids#storage-guidance for more details.',
    )
    notificationParameters: Optional[
        Dict[str, GoogleCloudSaasacceleratorManagementProvidersV1NotificationParameter]
    ] = Field(
        None,
        description='Optional. notification_parameter are information that service producers may like to include that is not relevant to Rollout. This parameter will only be passed to Gamma and Cloud Logging for notification/logging purpose.',
    )
    producerMetadata: Optional[Dict[str, str]] = Field(
        None,
        description='Output only. Custom string attributes used primarily to expose producer-specific information in monitoring dashboards. See go/get-instance-metadata.',
    )
    provisionedResources: Optional[
        List[GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource]
    ] = Field(
        None,
        description='Output only. The list of data plane resources provisioned for this instance, e.g. compute VMs. See go/get-instance-metadata.',
    )
    slmInstanceTemplate: Optional[str] = Field(
        None,
        description="Link to the SLM instance template. Only populated when updating SLM instances via SSA's Actuation service adaptor. Service producers with custom control plane (e.g. Cloud SQL) doesn't need to populate this field. Instead they should use software_versions.",
    )
    sloMetadata: Optional[
        GoogleCloudSaasacceleratorManagementProvidersV1SloMetadata
    ] = Field(
        None,
        description='Output only. SLO metadata for instance classification in the Standardized dataplane SLO platform. See go/cloud-ssa-standard-slo for feature description.',
    )
    softwareVersions: Optional[Dict[str, str]] = Field(
        None,
        description='Software versions that are used to deploy this instance. This can be mutated by rollout services.',
    )
    state: Optional[State] = Field(
        None,
        description="Output only. Current lifecycle state of the resource (e.g. if it's being created or ready to use).",
    )
    tenantProjectId: Optional[str] = Field(
        None,
        description='Output only. ID of the associated GCP tenant project. See go/get-instance-metadata.',
    )
    updateTime: Optional[str] = Field(
        None, description='Output only. Timestamp when the resource was last modified.'
    )
